### ISSUE TITLE
Relative file paths

### ISSUE THREAD

**Issue by Straskal** [tomblind/local-lua-debugger-vscode#11]
Hi there!

I'm having issues regarding **relative file paths** for assets (images) and **require paths** (other lua files).

- It appears that when running my program through the debugger, all paths are relative to the ```lldebugger.lua``` instead of the ```lua53.exe```.

I have my ```launch.json``` configured to use the ```lua53.exe``` interpreter and ```main.lua``` as my entry file.

Folder structure:
- lua53.exe
- main.lua
- imageLoader.lua
- assets
  - image.png

main.lua is not able to find imageLoader.lua via ```require()```

I bundled the two files together to avoid ```require()```, but then my program is unable to find the image.

Any help or work arounds would be greatly appreciated! 

Thank you.

**Comment by astrochili** [comment]
I have the same problem, can't require local lua modules.

**Comment by astrochili** [comment]
Found a dirty and hacky solution, run this before your requires:
```lua
local separator = string.sub(package.config, 1, 1)
local filePath = debug.getinfo(1).short_src
local rootFolder = string.gsub(filePath, "^(.+"..separator..")[^"..separator.."]+$", "%1");
package.path = rootFolder .. [[?.lua]]
```

**Comment by Straskal** [comment]
That work around works perfectly for now. @astrochili Thanks!

**Comment by tomblind** [comment]
Have you tried setting `cwd` in your launch.json?
```json
    "configurations": [
        {
            "name": "Debug",
            "type": "lua-local",
            "request": "launch",
            "program": {
                "lua": "lua53.exe",
                "file": "main.lua"
            },
            "cwd": "${workspaceFolder}"
        }
    ]
```

**Comment by astrochili** [comment]
> Have you tried setting `cwd` in your launch.json?

It doesn't help me, a similar error.

**Comment by astrochili** [comment]
Another problem is the luarocks libraries finding.

For example, luarocks installed the lume module to `/usr/local/var/homebrew/linked/luarocks/share/lua/5.3/lume.lua`. And the code `require("lume")` works perfectly with Lua in the terminal.

But the debugger tries to find modules in this list of paths:
```
no field package.preload['lume']
no file '/Users/.../.vscode/extensions/tomblind.local-lua-debugger-vscode-0.1.3/debugger/lume.lua'
no file '/usr/local/lib/lua/5.3/lume.so'
no file '/usr/local/lib/lua/5.3/loadall.so'
no file './lume.so'
```

**Comment by tomblind** [comment]
You're on OSX, right? It seems environment variables like `LUA_PATH` aren't passed to the child process in OSX (see #5). I don't have a Mac right now so I'll need to find one to debug this issue.

**Comment by tomblind** [comment]
Thinking about it, this issue must be different since the debugger script itself is being found.

**Comment by astrochili** [comment]
> You're on OSX, right?

Yes. Feel free to ask any questions or test tasks, maybe I can help you.

**Comment by astrochili** [comment]
Wow. Found a more clean solution in #10 that solves all my path finding problems. Just add this to debug configutation:
```json
"env": {
  "LUA_PATH": "./?.lua;[ADDITIONAL_PATHS]"
}
```
where `[ADDITIONAL_PATHS]` in my case is all that `luarocks path` terminal command returns. The final configuration looks like this:

```json
{
    "configurations": [
        {
            "name": "Debug",
            "type": "lua-local",
            "request": "launch",
            "program": {
              "lua": "lua5.3",
              "file": "${workspaceFolder}/main.lua"
            },
            "env": {
                "LUA_PATH": "./?.lua;/usr/local/Cellar/luarocks/3.2.1/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?/init.lua;/usr/local/lib/lua/5.3/?.lua;/usr/local/lib/lua/5.3/?/init.lua;./?.lua;./?/init.lua;/Users/username/.luarocks/share/lua/5.3/?.lua;/Users/username/.luarocks/share/lua/5.3/?/init.lua"
            }
        }
    ]
}
```

**Comment by tomblind** [comment]
It looks like `LUA_PATH` is not being passed to the debug adapter from vscode. Will you try this in your launch.json and see if it works?
```
"env": {
    "LUA_PATH": "${env:LUA_PATH}"
}
```

**Comment by astrochili** [comment]
Tried `"LUA_PATH": "a${env:LUA_PATH}b"` and It returned `no file 'ab'`.

**Comment by tomblind** [comment]
Thanks for the exhaustive testing! 😄 

It looks like `LUA_PATH` isn't being used to set `package.path`. If you don't mind, will you try testing with `LUA_PATH_5_3`? It's possible that's what your setup is using instead of `LUA_PATH`.

**Comment by astrochili** [comment]
Nope, the same situation:
- Tried "LUA_PATH": "a${env:LUA_PATH_5_3}b" in the configuration and It returned no file 'ab'.
- Tried echo $LUA_PATH in the terminal and it returned nothing. Should there be anything?

**Comment by tomblind** [comment]
In the terminal of vscode or an external one? There should be something in one of those two env variables, because that's where `package.path` is set from.

**Comment by astrochili** [comment]
I mean the external system terminal app, not VSCode.

With Lua in the terminal:
- `os.getenv("LUA_PATH")` -> nil
- `os.getenv("LUA_PATH_5_3")` -> nil
- `LUA_PATH` -> nil
- `LUA_PATH_5_3` -> nil

With debugger in VSCode:
- `os.getenv("LUA_PATH")` -> `/Users/.../.vscode/extensions/tomblind.local-lua-debugger-vscode-0.1.3/debugger/?.lua`
- `os.getenv("LUA_PATH_5_3")` -> nil
- `LUA_PATH` -> nil
- `LUA_PATH_5_3` -> nil

**Comment by tomblind** [comment]
Very strange, Lua must be getting its path from somewhere other than the standard env vars.

**Comment by tomblind** [comment]
On the terminal, can you type `declare` and see if any env vars reference those paths?

**Comment by astrochili** [comment]
I typed `declare` and there are no matches for these paths and for the word `lua`. Nothing 🤔.

**Comment by tomblind** [comment]
Well now I'm very confused 😆 It's got to be getting those paths from somewhere.

**Comment by astrochili** [comment]
Look at [this](https://www.lua.org/manual/5.3/manual.html#pdf-package.path), sounds like Lua get paths from `luaconf.h`. And it seems real because it have LUA_PATH_DEFAULT variable with my paths.

**Comment by tomblind** [comment]
Ah yeah, that's where it's getting the defaults. But how does it find the luarocks modules? You said before those work when running from terminal, right?

**Comment by astrochili** [comment]
Yea, it's simple because luarocks installs modules in these paths. For example luarocks module `lume` has a path `/usr/local/share/lua/5.3/lume.lua`. I don't know why `luarocks path` returns such long list of paths but I don't need them, as we see.

**Comment by tomblind** [comment]
Ahhh. Ok. Now it all makes sense 😄

**Comment by astrochili** [comment]
Yes, in short, the problem is that the debugger does not read the standard lua paths from lua conf.h. I don’t know what about LUA_PATH, because I don’t have it, maybe it doesn’t work too.

**Comment by Straskal** [comment]
"cwd": "${workspaceFolder}" definitely helped with loading assets. Thanks!

And it looks like everything's working! Awesome.
