### ISSUE TITLE
Breakpoints doesn't work on Windows with custom lua runtime

### ISSUE THREAD

**Issue by kozakt** [tomblind/local-lua-debugger-vscode#13]
Breakpoint doesn't work when using custom lua runtime on Windows platform.
This happen because of path to set breakpoint is wrongly formatted with forward slash instead of backslash for drive name.
Now it looks like this: C:/somefolder\anotherfolder\script.lua
And correct format should look like this: C:\somefolder\anotherfolder\script.lua

**Comment by tomblind** [comment]
Can you tell me what your custom runtime is? Or at least, what version of lua it is based on? Currently, the path separator is determined by [`package.config`](https://www.lua.org/manual/5.3/manual.html#pdf-package.config). Is it possible that is not available in your runtime?

**Comment by kozakt** [comment]
I'm using premake runtime https://premake.github.io/
Latest version is based on lua 5.3.5, but it's reproduced too with older versions based on lua 5.1.4
And yes, separator defined in package, but in file debugger/lldebugger.ts at line 126 you've added drive name to formatted path
``formattedPath = `${drive}${table.concat(pathParts, separator)}`;``
and drive name here contain wrong separator (C:/), like in my example above.
Other separators in path except the one after drive name are correct.

**Comment by tomblind** [comment]
Thanks - that's helpful info. It looks like premake's lua interpreter uses forward slashes for its paths and the debugger was failing to account for that when formatting.
