### ISSUE TITLE
Stops after setting the debugger hook even with stopOnEntry set to false

### ISSUE THREAD

**Issue by eduardomezencio** [tomblind/local-lua-debugger-vscode#28]
This happens when I use `"program": { "lua": "lua" }` or `"program": { "lua": "luajit" }` but does not happen when I use `"program": { "command": "love" }`. In both cases it seems `stopOnEntry` is ignored, but it always stops with lua and luajit and never stops with love. I don't know if this is intended or known or even if it happens in other systems, using linux here.

**Comment by tomblind** [comment]
I can't seem to reproduce this on my end. Can you post your launch.json?

One thing to keep in mind is that when using `"program": {"lua": "lua"}`, you should NOT have `require("lldebugger").start()` in your lua program. That would cause it to stop after that line, regardless of `stopOnEntry`.

However, when using a custom environment like love, you need that line, and it should respect `stopOnEntry`.

**Comment by eduardomezencio** [comment]
> One thing to keep in mind is that when using "program": {"lua": "lua"}, you should NOT have require("lldebugger").start() in your lua program. That would cause it to stop after that line, regardless of stopOnEntry.

This was the problem when using lua then.

Now, the part about love, I also can't reproduce it now, so I probably did something wrong when I tested it yesterday.

Thanks for your reply. I'll close the issue since it actually does not exist.
