### ISSUE TITLE
Strings containing escape characters

### ISSUE THREAD

**Issue by treahard** [tomblind/local-lua-debugger-vscode#30]
local sep = "\027" -- escape character
local s = "hello " .. sep .. " world"

print(s)

Place break point on print statement - local variable pane won't show variable 's'.

Continued debugging after stopping is difficult if not impossible.

**Comment by tomblind** [comment]
This has actually already been fixed in 1adb9faaa0f747a2f9de93a978c7a99d6685cbe9 and will be part of the next release, which I hope to put out soon.

**Comment by treahard** [comment]
Thank you.  Switching from ZeroBrane to VS Code with local-lua-debugger-vscode.
