### ISSUE TITLE
Correctly parse absolute paths on macOS & Linux in some cases

### ISSUE THREAD

**Issue by astrochili** [tomblind/local-lua-debugger-vscode#33]
https://github.com/tomblind/local-lua-debugger-vscode/blob/9849009ef3b9685d7a279fb0ab7b32b7a930ea2d/debugger/path.ts#L61

Do we really need to get the `drive` in this case?

I don't know about Windows but, for example, on macOS the path `'/path/to/there.lua'` will be separated to `'/'` and `'path/to/there.lua'` that is not correct. In this case file breakpoints and sources in the stack doesn't work. So I change
```
[drive, pathPart] = path.match('^[@=]?([\\/]*)(.*)');
```
to 
```
drive = ''
[drive, pathPart] = path.match(`^[@=]?[\\/]*(.*)`);
```
and then everything works fine because `isAbsolute` function also begins to work correctly. I think there is no way to detect is path the absolute or not on macOS and Linux by parsing the string.

The bugfix can make to be possible to use local-lua-debugger with [Defold](https://defold.com/) engine. I'm ready to prepare pull request with the instruction how to do it.

**Comment by astrochili** [comment]
Created a [guide](https://github.com/astrochili/defold-vscode-guide) how to use this debugger with Defold. It includes modified `lldebugger.lua` module with local fixes of https://github.com/tomblind/local-lua-debugger-vscode/issues/33 and https://github.com/defold/defold/issues/5703

**Comment by tomblind** [comment]
I'll look into what's going on here as I've tested this on linux and so it may be new bug.

**Comment by tomblind** [comment]
Sorry, just getting back around to this.

Can you give me an example of where this is breaking? `drive` is used to determine if it's absolute which is why it's split off even in unix and in `format` it is prepended back onto the path, so this should be working correctly as far as I can tell.

**Comment by thejustinwalsh** [comment]
I think I have a line on this error, as I am seeing (formatted for clarity)...
```json
[message]
{
   "tag":"$luaDebug",
   "type":"stack",
   "frames":[
      {
         "line":20,
         "source":"scripts/main.script",
         "mappedLocation":{
            "line":25,
            "source":"Users/thejustinwalsh/Projects/ts-defold/tsd-template/app/scripts/Users/thejustinwalsh/Projects/ts-defold/tsd-template/src/scripts/main.script.ts",
            "column":9
         },
         "active":true
      }
   ]
}
```
In the debugger verbose output.

The source map paths are defined as...
```json
{
   "version":3,
   "sources":[
      "/Users/thejustinwalsh/Projects/ts-defold/tsd-template/src/scripts/main.script.ts"
   ],
   "names":[
      "this"
   ],
   "file":"/Users/thejustinwalsh/Projects/ts-defold/tsd-template/src/scripts/main.script",
   "sourceRoot":""
}
```

It appears that an absolute path is being appended on-top of a relative path to the source roots.

<hr>

### tsconfig.json

```json
{
    "$schema": "https://raw.githubusercontent.com/TypeScriptToLua/vscode-typescript-to-lua/master/tsconfig-schema.json",
    "compilerOptions": {
        "target": "es2019",
        "lib": ["es2019"],
        "module": "commonjs",
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "moduleResolution": "node",
        "types": ["@ts-defold/types", "typescript-to-lua/language-extensions"],
        "typeRoots": ["@types", "node_modules/@types"],

        "rootDir": "src",
        "outDir": "app",
        "strict": true,
        "noUnusedLocals": false,
        "noUnusedParameters": false,
        "sourceMap": true,

        "plugins": [{ "name": "typescript-tstl-plugin" }],
    },
    "exclude": [
        "./node_modules/*",
        "./plugins/*"
    ],
    "tstl": {
        "luaTarget": "5.1",
        "luaLibImport": "require",
        "sourceMapTraceback": true,
        "trimExtensions": true,
        "luaPlugins": [
            {
                "name": "@ts-defold/tstl-export-as-global",
                "match": ".*\\.(?!editor_)script.ts$",
                "globals": { 
                    "functions": [ "init", "on_input", "on_message", "on_reload", "update", "final"]
                }
            },
            {
                "name": "@ts-defold/tstl-userdata-sugar"
            }
        ]
    }
}
```

<hr>

### launch.json

```json
{
  "version": "0.2.0",
  "configurations": [
      {
          "name": "Debug",
          "type": "lua-local",
          "request": "launch",
          "stopOnEntry": false,
          "verbose": true,
          "internalConsoleOptions": "openOnSessionStart",
          "program": { "command": "bash" },
          "osx": { "args": [".ts-defold/defold.sh", "launch", "macOS"] },
          "linux": { "args": [".ts-defold/defold.sh", "launch", "Linux"] },
          "windows": {
              "args": [".ts-defold/defold.sh", "launch", "Windows"],
              "program": { "command": "C:/Program Files/Git/bin/bash" }
          },
          "scriptRoots": [
              "app",
          ]
      }
  ]
}
```

**Comment by thejustinwalsh** [comment]
From the comment above if I run the two methods in the console...
<img width="754" alt="image" src="https://user-images.githubusercontent.com/72912/132483200-e8e0e4fc-8491-4925-97b5-57f8db3c9d25.png">

**Comment by tomblind** [comment]
The absolute path in sourcemaps is fixed, but I'm not sure this is the same issue, so I'm leaving this open for now.

**Comment by astrochili** [comment]
Sorry guys, I can’t check the case again at the moment. I’m migrated to Apple Silicon M1 but Defold building system ‘bob.jar' doesn’t work with M1 at the moment, so I just waiting for Defold updates.

**Comment by thejustinwalsh** [comment]
@astrochili I'm on an M1 as well, I just haven't tried to build with bob.jar yet. Everything else is working great though. :)
HMU if there is anything I can do to test / help in the meantime.

**Comment by thejustinwalsh** [comment]
@astrochili is #40 the same bug?

**Comment by astrochili** [comment]
Times change quickly, the M1 bug in Defold was fixed few months ago, so I'll check it out soon.

**Comment by astrochili** [comment]
> @astrochili is #40 the same bug?

I'm not sure, but with this bug breakpoints also did not work, because the debugger didn't understand what file they are in.

**Comment by astrochili** [comment]
Checked it. After fixing #40 the paths and breakpoints work now in my case. Closed :)
