### ISSUE TITLE
Crash when entering in mapSources function

### ISSUE THREAD

**Issue by redsigma** [tomblind/local-lua-debugger-vscode#36]
If i call a non existing function. The debugger will enter into this call, resulting in a crash

![image](https://user-images.githubusercontent.com/20425476/124963589-af579b80-e028-11eb-8783-94dd41ce7256.png)

If i wrap the code with the `.call(function() end)` then it no longer crashes and shows a nice error
![image](https://user-images.githubusercontent.com/20425476/124964019-2f7e0100-e029-11eb-9e3d-5caaa5eab08d.png)

I'd like to show this error in the console. I found out this can be done with `dbusted` and a `custom output handler` but the crash from the debugger still happens.

Adding a nill check at the first screenshot fixes the problem but i am not sure if it's the correct fix because if i use the function shown in the second screenshot then more stuff gets printed to console. In the first screenshot nothing is printed because of the nill check.

Another question is if there is any way to call the  `.call(function() end)` only once and affecting  all the tests instead of wrapping it around code ?

**Comment by tomblind** [comment]
Would you be able to share more of the code that causes this issue? I am not able to reproduce it just by calling a non-existent method.

**Comment by redsigma** [comment]
I am using the latest update and so far i can no longer reproduce this bug. I will post a unit test when i will be able to reproduce it.

I think you can close this for now.
