### ISSUE TITLE
[Suggestion] Using coxpcall for Lua 5.1 error resolution in coroutines

### ISSUE THREAD

**Issue by sewbacca** [tomblind/local-lua-debugger-vscode#41]
There is [a project](https://github.com/keplerproject/coxpcall), which replaces normal pcall and xpcall calls with coroutine compatible calls. It may be used to get stacktrace in Lua 5.1, which @tomblind mentioned in [#29](https://github.com/tomblind/local-lua-debugger-vscode/issues/29#issuecomment-915260405) is problematic.

**Comment by tomblind** [comment]
I looked into this when exploring that issue, but this method of replacing xpcall doesn't maintain the call stack in the error handler, so it would not allow breaking and inspecting at the error site. It would just break at the resume call as the debugger already does now.

**Comment by sewbacca** [comment]
Hmmm.... Sorry I didn't tested it before suggesting. I guess I'll close that issue now. Thank you.
