### ISSUE TITLE
Unable to build with TypeScriptToLua because `'lldebugger'` require path can't be resolved

### ISSUE THREAD

**Issue by cromo** [tomblind/local-lua-debugger-vscode#42]
I'm trying to get this extension working with TypeScriptToLua under LOVE, but when I build, I get
```
> yarn build
yarn run v1.22.11
$ yarn build:tstl && yarn build:copy
$ tstl -p tsconfig.json
error TSTL: Could not resolve require path 'lldebugger' in file src\main.ts.
```

I looked in your test cases but didn't see anything special that ought to make this error go away. I tried searching Github for the string `require("lldebugger").start()` in TypeScript files and the only result was your test case. Looking at other issues in this repo related to TypeScriptToLua and LOVE, it looks like no one else ran into this problem.

My project is based on the [LOVE TypeScript Template](https://github.com/hazzard993/love-typescript-template).

My `src\main.ts` is currently:
```typescript
if (os.getenv("LOCAL_LUA_DEBUGGER_VSCODE") == "1") {
  require("lldebugger").start();
}

love.load = () => {
  const [content] = love.filesystem.read("res/index.txt");
  print(content);
};

love.draw = () => {
  love.graphics.print("Hello World!", 400, 300);
};

```

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "lib": ["esnext"],
    "rootDir": "src",
    "outDir": "game",
    "types": [
      "lua-types/jit",
      "love-typescript-definitions",
      "typescript-to-lua/language-extensions"
    ]
  },
  "tstl": {
    "luaLibImport": "require",
    "luaTarget": "JIT",
    "noImplicitSelf": true,
    "sourceMapTraceback": true
  }
}
```

`.vscode\launch.json`, largely copy-pasted from the README:
```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Love",
      "type": "lua-local",
      "request": "launch",
      "program": {
        "command": "love"
      },
      "args": [
        "game"
      ],
      "scriptRoots": [
        "game"
      ]
    }
  ]
}
```

**Comment by tomblind** [comment]
This is due to extra checks reslution added by TSTL. There's a new compiler option `noResolvePaths` which has been added to address this, (see TypeScriptToLua/TypeScriptToLua#1101 and TypeScriptToLua/TypeScriptToLua#1139), but that is not available in the release version yet. Until TSTL has been updated, you can hack around this using:
```
if (os.getenv("LOCAL_LUA_DEBUGGER_VSCODE") === "1") {
    require("@NoResolution:lldebugger").start();
}
```

**Comment by cromo** [comment]
That got me building and able to add breakpoints to the compiled Lua code. To get breakpoints in TypeScript code working, I also had to add `"sourceMap": true` to my `tsconfig.json` under `compilerOptions`. (For the benefit of anyone else that hits this particular stumbling block.)

Resulting `tsconfig.json` for completion:
```json
{
  "compilerOptions": {
    "lib": [
      "esnext"
    ],
    "rootDir": "src",
    "outDir": "game",
    "types": [
      "lua-types/jit",
      "love-typescript-definitions",
      "typescript-to-lua/language-extensions"
    ],
    "sourceMap": true
  },
  "tstl": {
    "luaLibImport": "require",
    "luaTarget": "JIT",
    "noImplicitSelf": true,
    "sourceMapTraceback": true
  }
}
```
