### ISSUE TITLE
Feature request: Detect and highlight error from debug console

### ISSUE THREAD

**Issue by Sheepolution** [tomblind/local-lua-debugger-vscode#43]
I use Local Lua Debugger for running LÖVE, but I don't always require `lldebugger`, as that tends to slow down the game by a lot. I only do that when I actually want to debug something. However, one thing that's really nice about using the debugger is that when you get an error it will jump to that line and highlight it. I understand if it's not possible to do this without `lldebugger`, but the error also gets printed to the debug console. If possible, I would like Local Lua Debugger to read the contents of the debug console and interpret and highlight any error that appears in there.

If there is another solution to this, I would like to know. Perhaps with #20 the game doesn't run as slow and I can always be using `lldebugger`.

**Comment by tomblind** [comment]
This would be a good optimization to get in, so I'll leave this issue open for that.
