### ISSUE TITLE
Export environment vars? 

### ISSUE THREAD

**Issue by Shadowblitz16** [tomblind/local-lua-debugger-vscode#48]
I need to export `SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR=0` for love2d on linux.
How would I do this?

**Comment by tomblind** [comment]
You can pass environment variables by setting them in launch.json:
```
"env": {"SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR": "0"},
```
