### ISSUE TITLE
Restart Love2D don't just start a new one

### ISSUE THREAD

**Issue by Shadowblitz16** [tomblind/local-lua-debugger-vscode#49]
When running Love2D please restart it and don't just start a new one
![image](https://user-images.githubusercontent.com/2453707/146690482-6c6984c8-20e7-4272-ad12-e4198f2cb8ba.png)

**Comment by Shadowblitz16** [comment]
that's correct when love2d goes into error mode it doesn't close when I stop the process in vscode.

**Comment by tomblind** [comment]
Are you running on Windows, or something else?

**Comment by Shadowblitz16** [comment]
linux kubuntu 20.04
