### ISSUE TITLE
Luajit does not work in OSX

### ISSUE THREAD

**Issue by stuta** [tomblind/local-lua-debugger-vscode#5]
Launch json ```"program": { "lua": "/usr/local/bin/lua5.1"``` works.

But when I set ```"program": {  "lua": "/usr/local/bin/luajit-2.1.0-beta3"``` then I get error:
```
/usr/local/bin/luajit-2.1.0-beta3: ....local-lua-debugger-vscode-0.1.2/debugger/lldebugger.lua:1065: assertion failed!
stack traceback:
	[C]: in function 'assert'
	....local-lua-debugger-vscode-0.1.2/debugger/lldebugger.lua:1065: in function <....local-lua-debugger-vscode-0.1.2/debugger/lldebugger.lua:1048>
	[builtin:remove]: in function 'remove'
	....local-lua-debugger-vscode-0.1.2/debugger/lldebugger.lua:1219: in function 'popHook'
	....local-lua-debugger-vscode-0.1.2/debugger/lldebugger.lua:1247: in function 'runFile'
	(command line):1: in main chunk
	[C]: at 0x0100001680
```

**Comment by tomblind** [comment]
Is there specific lua code that causes this to occur, or does it happen with anything you try to debug?

If it's specific code, are you using coroutines?

**Comment by stuta** [comment]
It does not even start debugging my code.

**Comment by tomblind** [comment]
I've pushed an update that I think should fix your issue. Can you update the plugin and verify if it is resolved or not?

**Comment by stuta** [comment]
Something chnaged. Now it seems that debugger starts. It flashes very quickly debugger controls but then it ends in a fraction of a second without any error message.

Anso note that working lua5.1 debugger does not stop in first breakpoint, it stops in second breakpoint.

**Comment by stuta** [comment]
Everything has been working for a long time.
