### ISSUE TITLE
Can't debug io function in lua?

### ISSUE THREAD

**Issue by DFVSQY** [tomblind/local-lua-debugger-vscode#6]
Like below, it can't pause at `io.write(content)` line:
![gif](https://user-images.githubusercontent.com/8075421/67617467-0b0ed080-f816-11e9-8a96-0c0fa8b31f9d.gif)

Test Code:
``` lua
local filePath = "./res/test.txt"
local content = "file edit selection view goto debug terminal help\n"

local oldOut = io.output()
io.output(filePath)
io.write(content)
io.output(oldOut)

local oldIn = io.input()
io.input(filePath)
local text = io.read("*a")
print(text)
io.input(oldIn)
```

**Comment by tomblind** [comment]
Currently, the debugger uses stdin and stdout to communicate with the vscode plugin. Redirecting stdout with `io.output` breaks the communication.

If remote debugging is addded in the future (see #2), then debugging scripts which need to use stdin and stdout will be possible. But for now, this won't work.
